import Footer from '@/components/Footer';
import Header from '@/components/Header';
import '@/styles/globals.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gradient-to-tr from-green-100 to-red-100`}>
        <main className="flex min-h-screen flex-col">
          <Header title="Css Grid Auto Layout" />
          <div className="w-10/12 grow mx-auto flex flex-col justify-center">
            {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
